name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: pwd
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Delete OculusDB.exe
      run: rm 'Oculus Downgrader/bin/Debug/net6.0/OculusDB.exe'
    - name: Delete msedgedriver.exe
      run: rm 'Oculus Downgrader/bin/Debug/net6.0/msedgedriver.exe'
    - name: Upload net6.0.zip
      uses: actions/upload-artifact@v3
      with:
        name: net6.0
        path: 'Oculus Downgrader/bin/Debug/net6.0'
